CREATE DATABASE CARTEIRA;

USE CARTEIRA;

CREATE TABLE ATIVO (ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
					NOME VARCHAR(25) NOT NULL                    
                    );
                    
SELECT * FROM ATIVO;

DELETE FROM ATIVO WHERE ID > 1;